version: "2"
networks:
  distribuida:
    external:
      name: paralela_distribuida

services:
  postgres:
    image: postgres:9.6
    ports:
      - "56432:5432"
    environment:
          POSTGRES_USER: logica
          POSTGRES_PASSWORD: distribuida
          POSTGRES_DB: logicadb
    networks:
      - distribuida


